services:
  - type: web
    name: trader-onebox
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: RUN_TRADER
        value: "true"
      - key: USE_TESTNET
        value: "true"
      # add your real keys in the dashboard for this single service:
      # - key: DEEPSEEK_API_KEY
      # - key: BINANCE_API_KEY
      # - key: BINANCE_API_SECRET
      # optional tunables:
      # - key: SYMBOL
      #   value: "1000PEPEUSDT"
      # - key: INTERVAL
      #   value: "1m"
      # - key: KLIMIT
      #   value: "250"
